#define _GNU_SOURCE
#include <arpa/inet.h>
#include <errno.h>
#include <fcntl.h>
#include <netdb.h>
#include <poll.h>
#include <signal.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef HWELP_VERSION
#define HWELP_VERSION "0.1.0"
#endif
#define MAX_ROUTES 64
#define HDR_MAX 65536
#define CONN_MS 5000

enum scheme { DIRECT, SOCKS5, HTTPP };
struct route { char id[64], label[160], host[256], user[256], pass[256]; int port; enum scheme s; bool auth; };
struct req { bool connect; char method[16], host[256], path[4096], ver[16]; int port; };
static const char *lh="127.0.0.1", *rf="/tmp/podkop_bot/bearhole/routes.conf", *cf="/tmp/podkop_bot/bearhole/current"; static int lp=1066;

static int hp(const char *x,int dp,char *h,size_t z,int *p){const char *e,*c;if(!x||!*x)return-1;if(*x=='['){e=strchr(x,']');if(!e||(size_t)(e-x-1)>=z)return-1;memcpy(h,x+1,e-x-1);h[e-x-1]=0;*p=e[1]==':'?atoi(e+2):dp;}else{c=strrchr(x,':');if(c&&strchr(x,':')==c){size_t n=c-x;if(!n||n>=z)return-1;memcpy(h,x,n);h[n]=0;*p=atoi(c+1);}else{if(strlen(x)>=z)return-1;strcpy(h,x);*p=dp;}}return *p>0&&*p<65536?0:-1;}
static int hx(int c){if(c>='0'&&c<='9')return c-'0';c|=32;return c>='a'&&c<='f'?c-'a'+10:-1;}
static void urldec(char *s){char*r=s,*w=s;while(*r){if(*r=='%'&&hx(r[1])>=0&&hx(r[2])>=0){*w++=(hx(r[1])<<4)|hx(r[2]);r+=3;}else *w++=*r++;}*w=0;}
static int endpoint(const char *e,struct route*r){char b[1024],*q,*a,*c;if(!strcmp(e,"direct://")||!strcmp(e,"direct")){r->s=DIRECT;return 0;}if(strlen(e)>=sizeof(b))return-1;strcpy(b,e);q=strstr(b,"://");if(!q)return-1;*q=0;q+=3;if(!strcmp(b,"http"))r->s=HTTPP;else if(!strcmp(b,"socks5")||!strcmp(b,"socks5h"))r->s=SOCKS5;else return-1;r->auth=false;a=strrchr(q,'@');if(a){*a=0;c=strchr(q,':');if(c){*c=0;snprintf(r->user,sizeof(r->user),"%s",q);snprintf(r->pass,sizeof(r->pass),"%s",c+1);}else snprintf(r->user,sizeof(r->user),"%s",q);urldec(r->user);urldec(r->pass);r->auth=true;q=a+1;}return hp(q,r->s==HTTPP?8080:1080,r->host,sizeof(r->host),&r->port);}
static int routes(struct route *r){FILE*f=fopen(rf,"r");char*l=NULL,*p,*v[5];size_t z=0;ssize_t n;int k=0;if(!f)return 0;while(k<MAX_ROUTES&&(n=getline(&l,&z,f))>0){while(n&&(l[n-1]=='\n'||l[n-1]=='\r'))l[--n]=0;p=l;for(int i=0;i<5;i++)v[i]=strsep(&p,"|");if(!v[0]||!v[1]||!v[2])continue;memset(&r[k],0,sizeof(r[k]));snprintf(r[k].id,sizeof(r[k].id),"%s",v[0]);snprintf(r[k].label,sizeof(r[k].label),"%s",v[1]);if(!endpoint(v[2],&r[k]))k++;}free(l);fclose(f);f=fopen(cf,"r");if(f&&k>1){char id[64]={0};if(fgets(id,sizeof(id),f)){p=strpbrk(id,"|\n");if(p)*p=0;for(int i=1;i<k;i++)if(!strcmp(id,r[i].id)){struct route t=r[0];r[0]=r[i];r[i]=t;break;}}fclose(f);}else if(f)fclose(f);return k;}
static int nb(int f,bool on){int x=fcntl(f,F_GETFL,0);return x<0?-1:fcntl(f,F_SETFL,on?x|O_NONBLOCK:x&~O_NONBLOCK);}
static int conn(const char*h,int p){char ps[8];struct addrinfo hi={0},*a,*x;int f=-1,e;socklen_t ez=sizeof(e);snprintf(ps,sizeof(ps),"%d",p);hi.ai_socktype=SOCK_STREAM;hi.ai_family=AF_UNSPEC;if(getaddrinfo(h,ps,&hi,&a))return-1;for(x=a;x;x=x->ai_next){f=socket(x->ai_family,x->ai_socktype,x->ai_protocol);if(f<0)continue;nb(f,true);if(connect(f,x->ai_addr,x->ai_addrlen)<0&&errno!=EINPROGRESS){close(f);f=-1;continue;}struct pollfd q={f,POLLOUT,0};if(poll(&q,1,CONN_MS)<=0||getsockopt(f,SOL_SOCKET,SO_ERROR,&e,&ez)<0||e){close(f);f=-1;continue;}nb(f,false);break;}freeaddrinfo(a);return f;}
static int wr(int f,const void*b,size_t n){const char*p=b;while(n){ssize_t x=send(f,p,n,MSG_NOSIGNAL);if(x<0){if(errno==EINTR)continue;return-1;}if(!x)return-1;p+=x;n-=x;}return 0;}
static int rd(int f,void*b,size_t n){char*p=b;while(n){ssize_t x=recv(f,p,n,0);if(x<0){if(errno==EINTR)continue;return-1;}if(!x)return-1;p+=x;n-=x;}return 0;}
static int socks(struct route*r,const char*h,int p){int f=conn(r->host,r->port);unsigned char a[520],q[4],rep[4];size_t n=0;if(f<0)return-1;a[n++]=5;a[n++]=r->auth?2:1;a[n++]=0;if(r->auth)a[n++]=2;if(wr(f,a,n)||rd(f,rep,2)||rep[0]!=5||rep[1]==255)goto bad;if(rep[1]==2){size_t u=strlen(r->user),v=strlen(r->pass);if(u>255||v>255)goto bad;n=0;a[n++]=1;a[n++]=u;memcpy(a+n,r->user,u);n+=u;a[n++]=v;memcpy(a+n,r->pass,v);n+=v;if(wr(f,a,n)||rd(f,rep,2)||rep[1])goto bad;}else if(rep[1])goto bad;size_t hl=strlen(h);if(hl>255)goto bad;n=0;a[n++]=5;a[n++]=1;a[n++]=0;a[n++]=3;a[n++]=hl;memcpy(a+n,h,hl);n+=hl;a[n++]=p>>8;a[n++]=p;if(wr(f,a,n)||rd(f,q,4)||q[1])goto bad;size_t skip=q[3]==1?4:q[3]==4?16:0;if(q[3]==3){unsigned char l;if(rd(f,&l,1))goto bad;skip=l;}if(!skip)goto bad;if(rd(f,a,skip+2))goto bad;return f;bad:close(f);return-1;}
static const char B[]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";static char*b64(const char*s){size_t n=strlen(s),z=4*((n+2)/3),i=0,o=0;char*r=malloc(z+1);if(!r)return NULL;while(i<n){uint32_t a=(unsigned char)s[i++],b=i<n?(unsigned char)s[i++]:0,c=i<n?(unsigned char)s[i++]:0,v=a<<16|b<<8|c;r[o++]=B[v>>18&63];r[o++]=B[v>>12&63];r[o++]=B[v>>6&63];r[o++]=B[v&63];}if(n%3){r[z-1]='=';if(n%3==1)r[z-2]='=';}r[z]=0;return r;}
static int header(int f,char**o,size_t*z){char*b=malloc(HDR_MAX+1);size_t n=0;if(!b)return-1;while(n<HDR_MAX){ssize_t x=recv(f,b+n,HDR_MAX-n,0);if(x<=0){free(b);return-1;}n+=x;b[n]=0;if(strstr(b,"\r\n\r\n")){*o=b;*z=n;return 0;}}free(b);return-1;}
static int hconnect(struct route*r,const char*h,int p){int f=conn(r->host,r->port);char au[1024]="",rq[2048],*x=NULL,*e;size_t z;if(f<0)return-1;if(r->auth){char u[600];snprintf(u,sizeof(u),"%s:%s",r->user,r->pass);e=b64(u);if(!e){close(f);return-1;}snprintf(au,sizeof(au),"Proxy-Authorization: Basic %s\r\n",e);free(e);}int n=snprintf(rq,sizeof(rq),"CONNECT %s:%d HTTP/1.1\r\nHost: %s:%d\r\n%s\r\n",h,p,h,p,au);if(n<0||wr(f,rq,n)||header(f,&x,&z))goto bad;int code=0;sscanf(x,"HTTP/%*s %d",&code);free(x);if(code<200||code>=300)goto bad;return f;bad:if(x)free(x);close(f);return-1;}
static int request(const char*h,struct req*r){const char*e=strstr(h,"\r\n");char f[8192],t[4096];if(!e||(size_t)(e-h)>=sizeof(f))return-1;memcpy(f,h,e-h);f[e-h]=0;memset(r,0,sizeof(*r));if(sscanf(f,"%15s %4095s %15s",r->method,t,r->ver)!=3)return-1;if(!strcasecmp(r->method,"CONNECT")){r->connect=true;return hp(t,443,r->host,sizeof(r->host),&r->port);}if(!strncasecmp(t,"http://",7)){const char*a=t+7,*s=strchr(a,'/');char v[512];size_t n=s?(size_t)(s-a):strlen(a);if(!n||n>=sizeof(v))return-1;memcpy(v,a,n);v[n]=0;if(hp(v,80,r->host,sizeof(r->host),&r->port))return-1;snprintf(r->path,sizeof(r->path),"%s",s?s:"/");return 0;}const char*p=h;while((p=strstr(p,"\r\n"))){p+=2;if(!strncasecmp(p,"Host:",5)){p+=5;while(*p==' '||*p=='\t')p++;e=strstr(p,"\r\n");if(!e)return-1;char v[512];size_t n=e-p;if(n>=sizeof(v))return-1;memcpy(v,p,n);v[n]=0;if(hp(v,80,r->host,sizeof(r->host),&r->port))return-1;snprintf(r->path,sizeof(r->path),"%s",t);return 0;}}return-1;}
static void remember(struct route*r){char t[256];snprintf(t,sizeof(t),"%s.%ld",cf,(long)getpid());FILE*f=fopen(t,"w");if(f){fprintf(f,"%s|%s\n",r->id,r->label);fclose(f);rename(t,cf);}}
static void relay(int a,int b){struct pollfd p[2]={{a,POLLIN,0},{b,POLLIN,0}};char x[32768];for(;;){if(poll(p,2,-1)<0){if(errno==EINTR)continue;return;}for(int i=0;i<2;i++)if(p[i].revents&(POLLIN|POLLERR|POLLHUP)){ssize_t n=recv(p[i].fd,x,sizeof(x),0);if(n<=0||wr(p[1-i].fd,x,n))return;}}}
static int client(int c){char*b=NULL,*end;size_t z,hz;struct req q;struct route r[MAX_ROUTES];if(header(c,&b,&z)||request(b,&q)){free(b);return-1;}end=strstr(b,"\r\n\r\n");hz=end-b+4;int n=routes(r),u=-1,k=-1;for(int i=0;i<n;i++){u=q.connect?(r[i].s==DIRECT?conn(q.host,q.port):r[i].s==SOCKS5?socks(&r[i],q.host,q.port):hconnect(&r[i],q.host,q.port)):(r[i].s==HTTPP?conn(r[i].host,r[i].port):r[i].s==DIRECT?conn(q.host,q.port):socks(&r[i],q.host,q.port));if(u>=0){k=i;break;}}if(u<0){const char*x="HTTP/1.1 502 Bad Gateway\r\nConnection: close\r\n\r\n";wr(c,x,strlen(x));free(b);return-1;}remember(&r[k]);if(q.connect){const char*x="HTTP/1.1 200 Connection Established\r\nProxy-Agent: hwelp-proxy\r\n\r\n";if(wr(c,x,strlen(x)))goto out;}else if(r[k].s==HTTPP){if(r[k].auth){char up[600],*e,*tmp;snprintf(up,sizeof(up),"%s:%s",r[k].user,r[k].pass);e=b64(up);tmp=malloc(hz+strlen(e)+64);size_t pre=end-b;memcpy(tmp,b,pre);int m=snprintf(tmp+pre,hz+strlen(e)+64-pre,"\r\nProxy-Authorization: Basic %s\r\n\r\n",e);free(e);if(wr(u,tmp,pre+m)){free(tmp);goto out;}free(tmp);}else if(wr(u,b,hz))goto out;}else{const char*e=strstr(b,"\r\n");char f[8192];int m=snprintf(f,sizeof(f),"%s %s %s\r\n",q.method,q.path[0]?q.path:"/",q.ver);if(m<0||wr(u,f,m)||wr(u,e+2,hz-(e+2-b)))goto out;}if(z>hz&&wr(u,b+hz,z-hz))goto out;free(b);relay(c,u);close(u);return 0;out:free(b);close(u);return-1;}
static int bindfd(bool check){if(strcmp(lh,"127.0.0.1")&&strcmp(lh,"::1")){errno=EACCES;return-1;}int af=strchr(lh,':')?AF_INET6:AF_INET,f=socket(af,SOCK_STREAM,0),one=1;if(f<0)return-1;setsockopt(f,SOL_SOCKET,SO_REUSEADDR,&one,sizeof(one));int x;if(af==AF_INET){struct sockaddr_in a={.sin_family=AF_INET,.sin_port=htons(lp)};inet_pton(AF_INET,"127.0.0.1",&a.sin_addr);x=bind(f,(void*)&a,sizeof(a));}else{struct sockaddr_in6 a={.sin6_family=AF_INET6,.sin6_port=htons(lp)};inet_pton(AF_INET6,"::1",&a.sin6_addr);x=bind(f,(void*)&a,sizeof(a));}if(x<0){close(f);return-1;}if(!check&&listen(f,64)<0){close(f);return-1;}return f;}
static int self(void){struct route r={0};struct req q;char h[64];int p;return endpoint("socks5h://u:p%40s@127.0.0.1:1080",&r)||strcmp(r.pass,"p@s")||request("CONNECT github.com:443 HTTP/1.1\r\n\r\n",&q)||hp("[::1]:1080",80,h,sizeof(h),&p)||p!=1080;}
int main(int ac,char**av){bool ck=false,cb=false;for(int i=1;i<ac;i++)if(!strcmp(av[i],"-l")&&i+1<ac)lh=av[++i];else if(!strcmp(av[i],"-p")&&i+1<ac)lp=atoi(av[++i]);else if(!strcmp(av[i],"-c")&&i+1<ac)rf=av[++i];else if(!strcmp(av[i],"--check"))ck=true;else if(!strcmp(av[i],"--check-bind"))cb=true;else if(!strcmp(av[i],"--version")){puts("hwelp-proxy " HWELP_VERSION);return 0;}else return 2;if(lp<1024||lp>65535)return 2;if(ck){int x=self();if(!x)puts("hwelp proxy: check ok");return x;}if(cb){int f=bindfd(true);if(f<0){fprintf(stderr,"hwelp proxy: cannot bind 127.0.0.1:%d: %s\n",lp,strerror(errno));return errno==EADDRINUSE?3:1;}close(f);return 0;}signal(SIGPIPE,SIG_IGN);signal(SIGCHLD,SIG_IGN);int l=bindfd(false);if(l<0){fprintf(stderr,"hwelp proxy: cannot bind 127.0.0.1:%d: %s\n",lp,strerror(errno));return 1;}fprintf(stderr,"hwelp proxy: listening on 127.0.0.1:%d\n",lp);for(;;){int c=accept(l,NULL,NULL);if(c<0){if(errno==EINTR)continue;break;}pid_t p=fork();if(!p){close(l);client(c);close(c);_exit(0);}close(c);}return 1;}
