from pathlib import Path

# provider state
p=Path('root/usr/lib/podkop_bot/tsnet-provider.sh'); s=p.read_text()
s=s.replace('_enabled="$1"; _host="$2"; _url="$3"; _key="$4"; _adv="$5"', '_enabled="$1"; _host="$2"; _url="$3"; _key="$4"; _adv="$5"; _accept="${6:-false}"', 1)
s=s.replace('--argjson advertise_exit_node "$_adv" \\\n        --arg tag', '--argjson advertise_exit_node "$_adv" \\\n        --argjson accept_routes "$_accept" \\\n        --arg tag', 1)
s=s.replace('{provider:$provider,enabled:$enabled,hostname:$hostname,control_url:$control_url,auth_key:$auth_key,advertise_exit_node:$advertise_exit_node,tag:$tag,state_directory:$state_directory}', '{provider:$provider,enabled:$enabled,hostname:$hostname,control_url:$control_url,auth_key:$auth_key,accept_routes:$accept_routes,advertise_exit_node:$advertise_exit_node,tag:$tag,state_directory:$state_directory}', 1)
p.write_text(s)

# overlay endpoint
p=Path('root/usr/lib/podkop_bot/tsnet-overlay-watch.sh'); s=p.read_text()
s=s.replace('    _adv=$(tsnet_state_get advertise_exit_node)\n    _state=', '    _adv=$(tsnet_state_get advertise_exit_node)\n    _accept=$(tsnet_state_get accept_routes)\n    [ "$_accept" = true ] || _accept=false\n    _state=', 1)
s=s.replace('        --argjson advertise_exit_node "${_adv:-false}" \\\n        \'{type:"tailscale",tag:$tag,state_directory:$state_directory}', '        --argjson advertise_exit_node "${_adv:-false}" \\\n        --argjson accept_routes "${_accept:-false}" \\\n        \'{type:"tailscale",tag:$tag,state_directory:$state_directory,accept_routes:$accept_routes}', 1)
p.write_text(s)

# backend
p=Path('root/usr/libexec/rpcd/podkop_bot_tailscale'); s=p.read_text()
anchor='''auth_url() {
    _auth=$(logread 2>/dev/null | grep -F 'Waiting for authentication:' | tail -n 1 | sed 's/.*Waiting for authentication:[[:space:]]*//')
    case "$_auth" in http://*|https://*) printf '%s' "$_auth" ;; esac
}
'''
extra=anchor+'''\nsingbox_running() {\n    if [ -x /etc/init.d/sing-box ]; then /etc/init.d/sing-box running >/dev/null 2>&1 && return 0; fi\n    pidof sing-box >/dev/null 2>&1\n}\nruntime_endpoint_applied() {\n    _cfg=$(tsnet_config_path); [ -r "$_cfg" ] || return 1\n    _tag="$1"\n    if [ -n "$_tag" ]; then jq -e --arg t "$_tag" '(.endpoints // []) | any(.type=="tailscale" and .tag==$t)' "$_cfg" >/dev/null 2>&1\n    else jq -e '(.endpoints // []) | any(.type=="tailscale")' "$_cfg" >/dev/null 2>&1; fi\n}\nclash_connections() {\n    _cfg=$(tsnet_config_path); [ -r "$_cfg" ] || return 1\n    _ctl=$(jq -r '.experimental.clash_api.external_controller // empty' "$_cfg" 2>/dev/null); [ -n "$_ctl" ] || return 1\n    case "$_ctl" in http://*|https://*) _base="$_ctl" ;; *) _base="http://$_ctl" ;; esac\n    curl -fsS --connect-timeout 1 --max-time 2 "${_base%/}/connections" 2>/dev/null\n}\n'''
if anchor not in s: raise SystemExit('auth anchor')
s=s.replace(anchor,extra,1)
s=s.replace("_configured=false; _enabled=false; _registered=false; _host=''; _url=''; _adv=false; _section=''; _integration=overlay", "_configured=false; _enabled=false; _registered=false; _host=''; _url=''; _adv=false; _accept=false; _section=''; _integration=overlay",1)
s=s.replace('[ "$(uci -q get forkop.${_section}.tailscale_advertise_exit_node 2>/dev/null)" = 1 ] && _adv=true', '[ "$(uci -q get forkop.${_section}.tailscale_advertise_exit_node 2>/dev/null)" = 1 ] && _adv=true\n            [ "$(uci -q get forkop.${_section}.tailscale_accept_routes 2>/dev/null)" = 1 ] && _accept=true',1)
s=s.replace('[ "$(tsnet_state_get advertise_exit_node)" = true ] && _adv=true', '[ "$(tsnet_state_get advertise_exit_node)" = true ] && _adv=true\n        [ "$(tsnet_state_get accept_routes)" = true ] && _accept=true',1)
marker='''    jq -cn --arg provider "$_provider" --arg integration "$_integration" --arg ver "$_ver" \\
'''
health='''    _sb=false; singbox_running && _sb=true\n    _applied=false\n    if [ "$_configured" = true ]; then\n        if [ "$_integration" = overlay ]; then runtime_endpoint_applied "$TSNET_ENDPOINT_TAG" && _applied=true\n        else runtime_endpoint_applied "" && _applied=true; fi\n    fi\n    _active=0; _peers='[]'\n    if [ "$_enabled" = true ] && [ "$_sb" = true ]; then\n        _cj=$(clash_connections 2>/dev/null || true)\n        if [ -n "$_cj" ]; then\n            if [ "$_integration" = overlay ]; then\n                _match="tailscale/$TSNET_ENDPOINT_TAG"\n                _active=$(printf '%s' "$_cj" | jq -r --arg t "$_match" '[.connections[]? | select(.metadata.type==$t)] | length' 2>/dev/null || echo 0)\n                _peers=$(printf '%s' "$_cj" | jq -c --arg t "$_match" '[.connections[]? | select(.metadata.type==$t) | .metadata.sourceIP] | map(select(. != "")) | unique' 2>/dev/null || echo '[]')\n            else\n                _active=$(printf '%s' "$_cj" | jq -r '[.connections[]? | select(.metadata.type|startswith("tailscale/"))] | length' 2>/dev/null || echo 0)\n                _peers=$(printf '%s' "$_cj" | jq -c '[.connections[]? | select(.metadata.type|startswith("tailscale/")) | .metadata.sourceIP] | map(select(. != "")) | unique' 2>/dev/null || echo '[]')\n            fi\n        fi\n    fi\n    case "$_active" in ''|*[!0-9]*) _active=0 ;; esac\n    if [ "$_configured" != true ]; then _runtime_state=unconfigured\n    elif [ "$_enabled" != true ]; then _runtime_state=disabled\n    elif [ "$_sb" != true ]; then _runtime_state=failed\n    elif [ "$_applied" != true ]; then _runtime_state=degraded\n    elif [ "$_active" -gt 0 ]; then _runtime_state=active\n    elif [ "$_registered" = true ]; then _runtime_state=ready\n    else _runtime_state=starting; fi\n\n'''+marker
if marker not in s: raise SystemExit('status anchor')
s=s.replace(marker,health,1)
s=s.replace('--argjson registered "$_registered" --argjson adv "$_adv" --arg host', '--argjson registered "$_registered" --argjson adv "$_adv" --argjson accept "$_accept" --arg host',1)
s=s.replace('--argjson legacy_enabled "$_legacy_enabled" --arg legacy_host "$_legacy_host" --arg legacy_url "$_legacy_url" \\\n        \'{ok:true', '--argjson legacy_enabled "$_legacy_enabled" --arg legacy_host "$_legacy_host" --arg legacy_url "$_legacy_url" \\\n        --argjson sb "$_sb" --argjson applied "$_applied" --argjson active "$_active" --argjson peers "$_peers" --arg runtime_state "$_runtime_state" \\\n        \'{ok:true',1)
s=s.replace('enabled:$enabled,advertise_exit_node:$adv,registered:$registered,auth_url:$auth_url', 'enabled:$enabled,accept_routes:$accept,advertise_exit_node:$adv,registered:$registered,runtime_applied:$applied,singbox_running:$sb,active_connections:$active,active_peers:$peers,runtime_state:$runtime_state,auth_url:$auth_url',1)
s=s.replace('_adv=$(printf \'%s\' "$_IN" | jq -r \'.advertise_exit_node // false\')', '_adv=$(printf \'%s\' "$_IN" | jq -r \'.advertise_exit_node // false\')\n    _accept=$(printf \'%s\' "$_IN" | jq -r \'.accept_routes // false\')',1)
s=s.replace('case "$_adv" in true|1) _adv=true ;; false|0) _adv=false ;; *) return 5 ;; esac\n    return 0', 'case "$_adv" in true|1) _adv=true ;; false|0) _adv=false ;; *) return 5 ;; esac\n    case "$_accept" in true|1) _accept=true ;; false|0) _accept=false ;; *) return 6 ;; esac\n    return 0',1)
s=s.replace('5) printf \'{"ok":false,"reason":"bad_advertise_value"}\\n\'; return ;; esac', '5) printf \'{"ok":false,"reason":"bad_advertise_value"}\\n\'; return ;; 6) printf \'{"ok":false,"reason":"bad_accept_routes_value"}\\n\'; return ;; esac',1)
s=s.replace('[ $_ok = 1 ] && uci -q set "forkop.${_sec}.tailscale_advertise_exit_node=$_advi" || _ok=0', '[ $_ok = 1 ] && uci -q set "forkop.${_sec}.tailscale_advertise_exit_node=$_advi" || _ok=0\n        _acci=0; [ "$_accept" = true ] && _acci=1\n        [ $_ok = 1 ] && uci -q set "forkop.${_sec}.tailscale_accept_routes=$_acci" || _ok=0',1)
s=s.replace('tsnet_state_write false "$_host" "$_url" "$_key" "$_adv"', 'tsnet_state_write false "$_host" "$_url" "$_key" "$_adv" "$_accept"',1)
idx=s.index('method_set_advertise() {')
acceptfn='''method_set_accept_routes() {\n    json_in; _provider=$(tsnet_provider); _v=$(printf '%s' "$_IN" | jq -r '.enabled // false')\n    case "$_v" in true|1) _want=true ;; false|0) _want=false ;; *) printf '{"ok":false,"reason":"bad_value"}\\n'; return ;; esac\n    if [ "$_provider" = forkop-native ]; then\n        _sec=$(native_find_section); [ -n "$_sec" ] || { printf '{"ok":false,"reason":"not_configured"}\\n'; return; }\n        _vi=0; [ "$_want" = true ] && _vi=1\n        uci -q set "forkop.${_sec}.tailscale_accept_routes=$_vi" && uci -q commit forkop || { printf '{"ok":false,"reason":"uci_write_failed"}\\n'; return; }\n        [ "$(uci -q get forkop.${_sec}.enabled 2>/dev/null)" = 1 ] && native_restart >/dev/null 2>&1 || true\n    else\n        [ -r "$TSNET_STATE_FILE" ] || { printf '{"ok":false,"reason":"not_configured"}\\n'; return; }\n        _tmp="$TSNET_STATE_FILE.$$"; jq --argjson v "$_want" '.accept_routes=$v' "$TSNET_STATE_FILE" >"$_tmp" && chmod 600 "$_tmp" && mv -f "$_tmp" "$TSNET_STATE_FILE" || { rm -f "$_tmp"; printf '{"ok":false,"reason":"state_write_failed"}\\n'; return; }\n        [ "$(tsnet_state_get enabled)" = true ] && overlay_apply >/dev/null 2>&1 || true\n    fi\n    jq -cn --argjson accept_routes "$_want" '{ok:true,accept_routes:$accept_routes}'\n}\n\n'''
s=s[:idx]+acceptfn+s[idx:]
s=s.replace('"create":{"control_url":"","auth_key":"","hostname":"","advertise_exit_node":false,"confirm_standalone":false}', '"create":{"control_url":"","auth_key":"","hostname":"","accept_routes":false,"advertise_exit_node":false,"confirm_standalone":false}',1)
s=s.replace('"set_enabled":{"enabled":false,"confirm_standalone":false},"set_advertise_exit_node"', '"set_enabled":{"enabled":false,"confirm_standalone":false},"set_accept_routes":{"enabled":false},"set_advertise_exit_node"',1)
s=s.replace('set_enabled) method_set_enabled ;;\n            set_advertise_exit_node)', 'set_enabled) method_set_enabled ;;\n            set_accept_routes) method_set_accept_routes ;;\n            set_advertise_exit_node)',1)
p.write_text(s)

p=Path('Makefile'); s=p.read_text(); assert 'PKG_RELEASE:=60' in s; p.write_text(s.replace('PKG_RELEASE:=60','PKG_RELEASE:=61',1))
